# Generated by Django 6.0.1 on 2026-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_shipping_address_order_shipping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewasteitem',
            name='collection_address',
            field=models.TextField(blank=True, help_text='Full address for agent to collect from', null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='collection_district',
            field=models.CharField(blank=True, help_text='District for pickup', max_length=100, null=True),
        ),
    ]
