# Generated by Django 6.0.1 on 2026-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ewasteitem_collection_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer'), ('AGENT', 'Field Agent'), ('MECHANIC', 'Restoration Engineer')], default='CUSTOMER', max_length=10),
        ),
    ]
