# Generated by Django 6.0.1 on 2026-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ewasteitem_repair_progress_alter_ewasteitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewasteitem',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='parts_replaced',
            field=models.TextField(blank=True, help_text='List of components replaced during restoration', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='ewasteitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Assigned to Agent', 'Assigned to Agent'), ('Collected', 'Collected'), ('Assigned to Mechanic', 'Assigned to Mechanic'), ('Restoration in Progress', 'Restoration in Progress'), ('Restoration Complete', 'Restoration Complete'), ('Rework Requested', 'Rework Requested'), ('Awaiting Collection from Mechanic', 'Awaiting Collection from Mechanic'), ('Collected from Mechanic', 'Collected from Mechanic'), ('Repaired', 'Repaired'), ('Converted to Product', 'Converted to Product')], default='Pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned to Agent'), ('Picked Up', 'Picked Up from Hub'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
