# Generated by Django 6.0.1 on 2026-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_repairlog_is_paid_repairlog_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewasteitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewasteitem',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ewasteitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending (Upload)'), ('Approved', 'Approved'), ('Assigned to Agent', 'With Agent (Retaining)'), ('Collected', 'Collected (In Transit)'), ('Assigned to Mechanic', 'In Repair (At Mechanic)'), ('Restoration in Progress', 'Restoration in Progress'), ('Restoration Complete', 'Restoration Complete'), ('Rework Requested', 'Rework Requested'), ('Awaiting Collection from Mechanic', 'Awaiting Retrieval'), ('Collected from Mechanic', 'At Hub (Post-Repair)'), ('Repaired', 'Repaired'), ('Converted to Product', 'Listed for Sale'), ('Sold Out', 'Sold Out')], default='Pending', max_length=40),
        ),
    ]
