# Generated by Django 6.0.1 on 2026-03-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_repair_progress_ewasteitem_repair_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='operation_zone',
            field=models.CharField(blank=True, help_text='Primary district of operation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='workstation_images',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivery_assigned', 'Delivery Assigned'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
    ]
